version: "3.0"
services:
  mysql:
    image: mysql:5.7
    container_name: pimcore-mysql
    working_dir: /pimcore
    volumes:
      - ./pimcore:/pimcore
      - ./data/pimcore:/var/lib/mysql
      - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/pimcore.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=pimcore
      - MYSQL_USER=pimcore
      - MYSQL_PASSWORD=pimcore
    ports:
      - 33060:3306

  redis:
    build: docker/redis
    container_name: pimcore-redis

  webserver:
    build: docker/php-fpm
    container_name: pimcore-web
    working_dir: /pimcore
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
      - COMPOSER_ALLOW_SUPERUSER=1
    volumes:
      - ./pimcore:/pimcore
    ports:
      - 80:80
      - 443:443
